### ISSUE TITLE
Update to 1.11

### ISSUE THREAD

**Issue by eirikh1996** [misson20000/CBWrapper#5]
This plugin should be updated to 1.11

**Comment by misson20000** [comment]
This plugin is dead and has no use case anymore.

**Comment by MartinHavo** [comment]
Im using this plugin till this date and it's awesome. Why you think, thera are no uses? It's great for building minigames or automines.

**Comment by eirikh1996** [comment]
How do I get it to work with 1.11 then?

**Comment by MartinHavo** [comment]
Uhm, i rewrited code.

**Comment by misson20000** [comment]
We have vanilla commands for working with blocks that we didn't have when I first made this plugin. There's no need to use worldedit with command blocks anymore

**Comment by eirikh1996** [comment]
Also, @misson20000 since you no longer continue this plugin, I do have an interest to continue its development
